version: '3'
services:
  app:
    image: php:8.3-fpm
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
      - reverb
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: central_db
  redis:
    image: redis:alpine
  reverb:
    image: ghcr.io/laravel/reverb:latest
    depends_on:
      - redis
    environment:
      APP_KEY: ${APP_KEY}
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: ${REVERB_HOST}
      REVERB_PORT: ${REVERB_PORT}
    ports:
      - "${REVERB_PORT:-8080}:8080"
  horizon:
    image: php:8.3-fpm
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
      - reverb
    command: php artisan horizon
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
