version: '3'
services:
  app:
    image: php:8.3-fpm
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: central_db
  redis:
    image: redis:alpine
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
