# Environment:
# - Requires Docker 20+ and Docker Compose 1.29+
# - Services: app (PHP), MySQL 8.0, Redis (alpine), Nginx (alpine)

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elitesaas-app
    container_name: elitesaas-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: elitesaas-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elitesaas
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: elitesaas-redis
    restart: unless-stopped
    ports:
      - 6379:6379

  nginx:
    image: nginx:alpine
    container_name: elitesaas-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
