openapi: 3.0.0
info:
  title: EliteSaaS API
  version: 1.0.0
servers:
  - url: http://localhost/api
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
  /pos/orders:
    post:
      summary: Create new order
      responses:
        '201':
          description: Order created
  /inventory/items:
    get:
      summary: List inventory items
      responses:
        '200':
          description: List of items
