version: '3'
services:
  app:
    image: php:8.3-fpm
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    environment:
      POS_MODULE_ENABLED: ${POS_MODULE_ENABLED:-true}
      INVENTORY_MODULE_ENABLED: ${INVENTORY_MODULE_ENABLED:-true}
      CRM_MODULE_ENABLED: ${CRM_MODULE_ENABLED:-false}
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-central_db}
  redis:
    image: redis:alpine
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
