openapi: 3.0.3
info:
  title: FloorPlanDesigner API
  version: 1.0.0
paths:
  /api/v1/floorplan/{id}:
    patch:
      summary: Update floorplan JSON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                json_data:
                  type: object
      responses:
        '200':
          description: Updated
  /api/v1/floorplan/{id}/zones:
    get:
      summary: List zones
      responses: { '200': { description: Ok } }
    post:
      summary: Create zone
      responses: { '201': { description: Created } }
  /api/v1/floorplan/{id}/publish:
    post: { summary: Publish plan, responses: { '200': { description: Ok } } }
  /api/v1/floorplan/{id}/archive:
    post: { summary: Archive plan, responses: { '200': { description: Ok } } }
  /api/v1/floorplan/{id}/schedule:
    post: { summary: Schedule plan, responses: { '200': { description: Ok } } }
  /api/v1/floorplan/export/{id}:
    get: { summary: Export plan, responses: { '200': { description: Ok } } }
  /api/v1/floorplan/import:
    post: { summary: Import plan, responses: { '201': { description: Created } } }
