name: Tests

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, dom, fileinfo
          coverage: none
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Setup environment
        run: cp .env.example .env && php artisan key:generate
      - name: Run migrations
        run: php artisan migrate --force
      - name: Run tests
        run: php artisan test
